#! /bin/sh

# #--- AUTOSTART ---# #
feh --randomize --bg-fill $HOME/Pictures/anu/* &
~/.config/polybar/launch.sh &

# #--- WORKSPACES ---# #
bspc monitor -d TERM CODE WEB BOOKS MUSIC EXTRA

# #--- WINDOW Configuration ---# #
bspc config border_width         4
bspc config window_gap           21
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#--- WINDOW RULES ---#
# bspc rule -a Chromium desktop='^3'
bspc rule -a Runner state=floating
bspc rule -a kitty rectangle=545x350+0+0 center=on
bspc rule -a love state=floating center=on

# #---BSPWM coloring---# #
bspc config normal_border_color     "#4c566a"
bspc config focused_border_color     "#ffffff"
