#! /bin/sh

# #--- AUTOSTART ---# #
sxhkd &
~/.config/polybar/launch.sh &

# #--- WORKSPACES ---# #
bspc monitor -d HOME TERM CODE WEB BOOKS MUSIC EXTRA

# #--- WINDOW Configuration ---# #
bspc config border_width         4
bspc config window_gap           21
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#--- WINDOW RULES ---#
bspc rule -a Surf       state=tiled
bspc rule -a Zathura    desktop=^5 follow=on state=tiled

# #---BSPWM coloring---# #
bspc config normal_border_color "#44475a"
bspc config active_border_color "#bd93f9"
bspc config focused_border_color "#ff79c6"
bspc config presel_feedback_color "#6272a4"
